pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('myproject') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('myproject') {
                    bat 'docker build -t myproject:v1 .'
                }
            }
        }

    }
}
