pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Build') {
            steps {
                dir('myproject') {
                bat 'mvn clean package'
            }
        }

    }
}